from __future__ import annotations

import os
import pwd
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
from typing import Optional

from lib.apt_sources import ensure_debian_package_sources
from lib.system_utils import get_current_username
from lib.validation import validate_filesystem_path
from lib.validators import validate_username

BASE_PACKAGES = [
    "ca-certificates",
    "python3",
    "python3-venv",
    "curl",
    "git",
    "openssh-client",
    "rsync",
    "tar",
]

LAUNCHER_NAME = "infra_tools"
SYSTEM_LAUNCHER_DIR = "/usr/local/bin"
TMPFILES_CONF_PATH = "/etc/tmpfiles.d/infra_tools.conf"


def _resolve_project_script(script_path: str) -> str:
    """Return an absolute path to infra_tools.py for use inside the launcher."""
    resolved = script_path
    if not os.path.isabs(resolved):
        resolved = shutil.which(resolved) or os.path.abspath(resolved)
    return resolved


def _launcher_contents(project_script: str) -> str:
    return (
        "#!/bin/sh\n"
        "# Auto-generated by infra_tools bootstrap. Re-run "
        "`infra_tools bootstrap` to refresh.\n"
        f"exec python3 {shlex.quote(project_script)} \"$@\"\n"
    )


def install_launcher(
    script_path: str,
    *,
    target_dir: str,
    chown_to: Optional[tuple[int, int]] = None,
) -> str:
    """Write a small ``infra_tools`` launcher into ``target_dir``.

    Returns the path of the launcher created. The launcher execs the project
    ``infra_tools.py`` with ``python3`` so users can run ``infra_tools`` from
    any directory after bootstrap.
    """
    project_script = _resolve_project_script(script_path)
    if not os.path.isfile(project_script):
        raise ValueError(f"infra_tools script not found at {project_script}")
    os.makedirs(target_dir, exist_ok=True)
    launcher_path = os.path.join(target_dir, LAUNCHER_NAME)
    file_descriptor, temporary_path = tempfile.mkstemp(
        prefix=".infra_tools_launcher.",
        dir=target_dir,
        text=True,
    )
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as handle:
            handle.write(_launcher_contents(project_script))
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(
            temporary_path,
            stat.S_IRUSR
            | stat.S_IWUSR
            | stat.S_IXUSR
            | stat.S_IRGRP
            | stat.S_IXGRP
            | stat.S_IROTH
            | stat.S_IXOTH,
        )
        if chown_to is not None:
            os.chown(temporary_path, chown_to[0], chown_to[1])
        os.replace(temporary_path, launcher_path)
    finally:
        if os.path.exists(temporary_path):
            os.unlink(temporary_path)
    return launcher_path


def resolve_bootstrap_user(requested_user: Optional[str]) -> tuple[str, str]:
    """Resolve the local user whose shell environment should be configured."""
    if requested_user:
        username = requested_user
    elif os.geteuid() == 0 and os.environ.get("SUDO_USER"):
        username = os.environ["SUDO_USER"]
    else:
        username = get_current_username()

    if not validate_username(username):
        raise ValueError(f"Invalid username: {username}")

    try:
        home_dir = pwd.getpwnam(username).pw_dir
    except KeyError as exc:
        raise ValueError(f"User not found: {username}") from exc

    return username, home_dir


def retire_legacy_tmpfiles_conf(
    conf_path: str = TMPFILES_CONF_PATH,
) -> bool:
    """Remove the ineffective legacy tmpfiles config from older bootstraps."""
    validate_filesystem_path(conf_path, must_exist=False)
    if not os.path.exists(conf_path):
        return False
    if os.geteuid() != 0:
        raise PermissionError(
            "Removing the legacy tmpfiles.d configuration requires root privileges."
        )
    os.unlink(conf_path)
    return True


def install_system_packages(shell: str) -> int:
    """Install local system packages needed to operate infra_tools."""
    if os.geteuid() != 0:
        print("Error: System package installation requires root privileges. Re-run with sudo or use --skip-system-packages.")
        return 1

    if shutil.which("apt-get") is None:
        print("Error: automatic package installation requires apt-get on a Debian-based host.")
        return 1

    packages = list(BASE_PACKAGES)
    if shell == "bash":
        packages.append("bash-completion")

    try:
        ensure_debian_package_sources()
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"Error: could not prepare Debian APT sources: {exc}")
        return 1

    print(
        "Refreshing package lists (APT may wait for another package operation)...",
        flush=True,
    )
    apt_environment = os.environ.copy()
    apt_environment["DEBIAN_FRONTEND"] = "noninteractive"
    update_result = subprocess.run(
        [
            "apt-get",
            "-o",
            "DPkg::Lock::Timeout=120",
            "-o",
            "Dpkg::Use-Pty=0",
            "update",
            "-q",
        ],
        env=apt_environment,
        check=False,
    )
    if update_result.returncode != 0:
        print("Error: failed to update package lists; see the APT output above.")
        return 1

    print("Installing orchestration host packages...", flush=True)
    install_result = subprocess.run(
        [
            "apt-get",
            "-o",
            "DPkg::Lock::Timeout=120",
            "-o",
            "Dpkg::Use-Pty=0",
            "install",
            "-y",
            "-q",
            *packages,
        ],
        env=apt_environment,
        check=False,
    )
    if install_result.returncode != 0:
        print("Error: failed to install required packages; see the APT output above.")
        return 1

    print(f"✓ Installed system packages: {', '.join(packages)}", flush=True)
    return 0


def _resolve_self_command(script_path: str) -> list[str]:
    resolved_path = script_path
    if not os.path.isabs(resolved_path):
        resolved_path = shutil.which(resolved_path) or os.path.abspath(resolved_path)
    if resolved_path.endswith(".py"):
        return [sys.executable, resolved_path]
    return [resolved_path]


def run_orchestrator_bootstrap(
    script_path: str,
    shell: str,
    requested_user: Optional[str],
    skip_system_packages: bool = False,
) -> int:
    """Bootstrap a local orchestration host for infra_tools administration."""
    try:
        username, home_dir = resolve_bootstrap_user(requested_user)
    except ValueError as exc:
        print(f"Error: {exc}")
        return 1

    print(f"Bootstrapping orchestration host for {username}...")

    if not skip_system_packages:
        result = install_system_packages(shell)
        if result != 0:
            return result
        try:
            launcher_path = install_launcher(script_path, target_dir=SYSTEM_LAUNCHER_DIR)
            print(f"✓ Installed system launcher: {launcher_path}")
        except (OSError, ValueError) as exc:
            print(f"Error: could not install system launcher in {SYSTEM_LAUNCHER_DIR}: {exc}")
            return 1

    try:
        if retire_legacy_tmpfiles_conf():
            print(f"✓ Removed legacy systemd tmpfiles.d config: {TMPFILES_CONF_PATH}")
    except (OSError, PermissionError) as exc:
        print(f"Warning: could not remove legacy tmpfiles.d config: {exc}")

    command = _resolve_self_command(script_path) + [
        "python-tools",
        "--shell",
        shell,
        "--script-path",
        _resolve_project_script(script_path),
    ]
    current_username = get_current_username()
    if username == current_username:
        return subprocess.run(command, check=False).returncode

    if os.geteuid() != 0:
        print("Error: Switching to another user requires root privileges.")
        return 1

    env = os.environ.copy()
    env["HOME"] = home_dir
    env["USER"] = username
    return subprocess.run(
        ["runuser", "-u", username, "--", *command],
        env=env,
        check=False,
    ).returncode
